#define PLANE_SPACE -95
#define PLANE_SPACE_PARALLAX -90

#define RENDER_PLANE_NON_GAME 995

#define ATMOS_GROUP_PLANE 450
#define DISPLACEMENT_MAP_PLANE -69
#define GRAVITY_PULSE_PLANE -70
#define GRAVITY_PULSE_RENDER_TARGET "*GRAVPULSE_RENDER_TARGET"

#define RAD_TEXT_PLANE 90
